CurrencyPair precision
cassandre-tech/cassandre-trading-bot pull request #835
Opened 2021-12-01 12:37 UTC by xblaatx

2021-12-01 15:45 UTC, xblaatx commented
@straumat 

the closePosition method still needs to be changed. it gets the CurrencyPair from the tickerFlux. the baseCurrencyPrecision  and qouteCurrencyPrecision are not populated.

2021-12-02 21:02 UTC, straumat commented
Looks good but can you change comments on class variable. They should be one like like on other project files. Thx

2021-12-02 21:03 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +    /**
This comment should be on one lile

2021-12-03 07:54 UTC, straumat requested changes

2021-12-03 07:54 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +    int qouteCurrencyPrecision;
Sorry, there is a typo here: "qoute" instead of "quote"

2021-12-03 07:54 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +    public CurrencyPairDTO(final String newBaseCurrency, final String newQuoteCurrency, final int newBaseCurrencyPrecision, final int newQouteCurrencyPrecision) {
Same here "Qoute"

2021-12-03 07:54 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +    public CurrencyPairDTO(final String newBaseCurrency, final String newQuoteCurrency, final int newBaseCurrencyPrecision, final int newQouteCurrencyPrecision) {
here again "Qoute"

2021-12-03 07:54 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +        this.qouteCurrencyPrecision = newQouteCurrencyPrecision;
here again "Qoute"

2021-12-03 07:54 UTC, straumat commented on spring-boot-starter/autoconfigure/src/main/java/tech/cassandre/trading/bot/dto/util/CurrencyPairDTO.java
> +        this.qouteCurrencyPrecision = newQouteCurrencyPrecision;
here again "Qoute"

2021-12-03 07:55 UTC, straumat requested changes
Can you add amount.setScale(currencyPair.getBaseCurrencyPrecision(), FLOOR) to createLimitOrder() too ?

2021-12-03 08:38 UTC, straumat requested changes

2021-12-03 09:18 UTC, merged